# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xenon's Blog
email: me@xenonchau.com
description: > # this means to ignore newlines until "baseurl:"
  博客没啥可看的，都是屌丝程序员的一些吐槽。
baseurl: /blog_jekyll" # the subpath of your site, e.g. /blog
url: "https://xenonchau.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  xenonchau

# Build settings
markdown: kramdown
